# Generated by Django 3.0.14 on 2023-01-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_meetingtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtable',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meetingtable',
            name='time',
            field=models.TimeField(),
        ),
    ]
