# Generated by Django 3.0.14 on 2023-01-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20230113_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicname', models.CharField(max_length=50)),
                ('credit', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=30)),
                ('gpa', models.CharField(max_length=30)),
            ],
        ),
    ]
