# Generated by Django 3.0.14 on 2023-01-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_gradetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='EWUadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=60)),
                ('password', models.CharField(default='', max_length=60)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
