# Generated by Django 3.0.14 on 2023-01-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_ewuadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EWUadmin',
            new_name='Ad_panel',
        ),
    ]
