# Generated by Django 3.0.14 on 2023-01-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20230115_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_panel',
            name='first_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='ad_panel',
            name='last_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
